import { COLORS, SPACING, TYPOGRAPHY, BORDER_RADIUS, Z_INDEX, TRANSITIONS } from './design-tokens';

export const modalStyles = {
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.background.overlay,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: Z_INDEX.modal,
    animation: `fadeIn ${TRANSITIONS.fast} ${TRANSITIONS.ease}`,
    padding: SPACING.lg,
  },
  modal: {
    backgroundColor: COLORS.background.modal,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.xxl,
    width: '100%',
    maxWidth: '500px',
    maxHeight: '90vh',
    overflow: 'auto' as const,
    animation: `slideUp ${TRANSITIONS.fast} ${TRANSITIONS.ease}`,
    outline: 'none',
  },
  title: {
    margin: `0 0 ${SPACING.sm} 0`,
    fontSize: TYPOGRAPHY.fontSize.lg,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.text.primary,
    outline: 'none',
  },
  description: {
    margin: `0 0 ${SPACING.xxl} 0`,
    color: COLORS.text.secondary,
    fontSize: TYPOGRAPHY.fontSize.base,
  },
  buttonContainer: {
    display: 'flex',
    gap: SPACING.md,
    justifyContent: 'flex-end',
    marginTop: SPACING.xxl,
    flexWrap: 'wrap' as const,
  },
  cancelButton: {
    padding: `${SPACING.lg} ${SPACING.xl}`,
    border: `2px solid ${COLORS.secondary}`,
    borderRadius: BORDER_RADIUS.sm,
    backgroundColor: COLORS.background.transparent,
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    cursor: 'pointer' as const,
    transition: TRANSITIONS.all,
    minWidth: '80px',
  },
  submitButton: {
    padding: `${SPACING.lg} ${SPACING.xl}`,
    border: `2px solid ${COLORS.primary}`,
    borderRadius: BORDER_RADIUS.sm,
    backgroundColor: COLORS.primary,
    color: COLORS.text.inverse,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    transition: TRANSITIONS.all,
    minWidth: '80px',
  },
};

